# Generated by Django 5.0.13 on 2025-04-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyberbullying", "0002_userprofile_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image_analysis",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="text_analysis",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
