# Generated by Django 5.0.13 on 2025-04-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyberbullying", "0003_post_image_analysis_post_text_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
